### PR TITLE
example: add cargo-xtask usage

### PR DESCRIPTION
**Pull request by Binlogo**
Prepare an example "cargo xtask" use case mentioned in #7.

### CODE REVIEW

**Review by akesson — APPROVED** [review]
Looks good!

**Comment by Binlogo** [comment]
- [x] waiting https://github.com/akesson/rustup-configurator/pull/2 to merge

**Comment by Binlogo** [comment]
I should have fixed the tests by installing the targets first. Later, I'll try to figure out how to change the Rustup configurator's "interact" mode to "default" mode in the tests. 
Please review, thx. @akesson

**Comment by akesson** [comment]
The code looks good. There's some clippy warnings though. Could you fix them? And of course the tests.

**Review by akesson — CHANGES_REQUESTED** [review]
The code looks good. There's some clippy warnings though. Could you fix them? And of course the tests.

**Review by akesson — APPROVED** [review]

**Comment by akesson** [comment]
Thanks for the contribution!

**Pull request merged**
